# Generated by Django 6.0.7 on 2026-07-19 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_is_tech_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('markup_percent', models.FloatField(default=50, help_text='Наценка, %')),
                ('retail_price', models.FloatField(blank=True, help_text='Ручная розничная цена, сом (null = авто)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_products', to='accounts.shop')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('кг', 'килограмм'), ('л', 'литр'), ('гр', 'грамм'), ('мл', 'миллилитр'), ('шт', 'штука')], default='кг', max_length=5)),
                ('purchase_volume', models.FloatField(help_text='Объём закупа в unit: 50 (кг) = мешок')),
                ('purchase_price', models.FloatField(help_text='Цена всей партии, сом')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_ingredients', to='accounts.shop')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SemiFinished',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('batch_output', models.FloatField(help_text='Выход готового замеса, гр/мл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semi_finished', to='accounts.shop')),
            ],
            options={
                'verbose_name_plural': 'semi finished',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SemiIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(help_text='Расход в базовых единицах (гр/мл/шт)')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techcards.rawingredient')),
                ('semi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='techcards.semifinished')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(help_text='Гр/мл/шт на 1 десерт')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='techcards.finalproduct')),
                ('raw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='techcards.rawingredient')),
                ('semi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='techcards.semifinished')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('raw__isnull', False), ('semi__isnull', True)), models.Q(('raw__isnull', True), ('semi__isnull', False)), _connector='OR'), name='component_raw_xor_semi')],
            },
        ),
    ]
