# Generated by Django 6.0.7 on 2026-07-20 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_role_tech_admin'),
        ('techcards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Выпущено штук')),
                ('unit_cost', models.FloatField(help_text='Себестоимость 1 шт на момент выпуска, сом')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='techcards.finalproduct')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_runs', to='accounts.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('receipt', 'Приход сырья'), ('production_out', 'Расход в производство'), ('production_in', 'Выпуск продукции')], max_length=20)),
                ('quantity', models.FloatField(help_text='Знаковое: приход +, расход −')),
                ('unit_cost', models.FloatField(default=0, help_text='Себестоимость единицы на момент движения, сом')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='techcards.finalproduct')),
                ('raw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='techcards.rawingredient')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='techcards.productionrun')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='accounts.shop')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['shop', 'created_at'], name='techcards_s_shop_id_858d49_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', True), ('raw__isnull', False)), models.Q(('product__isnull', False), ('raw__isnull', True)), _connector='OR'), name='movement_raw_xor_product')],
            },
        ),
    ]
