# Generated by Django 6.0.7 on 2026-07-20 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_role_tech_admin'),
        ('techcards', '0002_productionrun_stockmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='kind',
            field=models.CharField(choices=[('receipt', 'Приход сырья'), ('production_out', 'Расход в производство'), ('production_in', 'Выпуск продукции'), ('sale', 'Отгрузка по накладной'), ('disposal', 'Списание')], max_length=20),
        ),
        migrations.CreateModel(
            name='Disposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('unit_cost', models.FloatField(help_text='Себестоимость единицы на момент списания, сом')),
                ('reason', models.CharField(choices=[('defect', 'Брак'), ('expired', 'Просрочка'), ('tasting', 'Тест / дегустация')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disposals', to='techcards.finalproduct')),
                ('raw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disposals', to='techcards.rawingredient')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposals', to='accounts.shop')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='disposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='techcards.disposal'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Номер вида 2026-0001', max_length=20)),
                ('date', models.DateField(help_text='Дата документа')),
                ('from_department', models.CharField(choices=[('workshop', 'Цех'), ('sales', 'Отдел продаж'), ('outlet', 'Точка продаж')], default='workshop', max_length=20)),
                ('to_client', models.CharField(help_text='Покупатель', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.shop')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='techcards.invoice'),
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('unit_cost', models.FloatField(help_text='Себестоимость 1 шт на момент отгрузки, сом')),
                ('sell_price', models.FloatField(help_text='Цена продажи 1 шт, сом')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='techcards.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='techcards.finalproduct')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='disposal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', True), ('raw__isnull', False)), models.Q(('product__isnull', False), ('raw__isnull', True)), _connector='OR'), name='disposal_raw_xor_product'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('shop', 'number'), name='invoice_number_per_shop'),
        ),
    ]
