# Generated by Django 6.0.7 on 2026-07-20 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_role_tech_admin'),
        ('techcards', '0003_alter_stockmovement_kind_disposal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalproduct',
            name='category',
            field=models.CharField(blank=True, help_text='Направление: Торты, Кофе, 3D десерты…', max_length=100),
        ),
        migrations.AddField(
            model_name='finalproduct',
            name='manual_unit_cost',
            field=models.FloatField(blank=True, help_text='Ручная себестоимость, сом (для позиций без техкарты)', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_imported',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FinanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.FloatField(default=0.04, help_text='Ставка налога/резерва, доля (0.04 = 4 %)')),
                ('opening_cash', models.FloatField(default=0, help_text='Остаток денег на начало года, сом')),
                ('target_profit', models.FloatField(default=0, help_text='Целевая чистая прибыль в месяц, сом')),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_settings', to='accounts.shop')),
            ],
            options={
                'verbose_name_plural': 'finance settings',
            },
        ),
        migrations.CreateModel(
            name='FixedCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.FloatField(default=0, help_text='Сумма в месяц, сом')),
                ('active', models.BooleanField(default=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_costs', to='accounts.shop')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flow', models.CharField(choices=[('in', 'Поступление'), ('out', 'Расход')], max_length=3)),
                ('pnl_article', models.CharField(help_text='Статья ОПиУ или «Не влияет на ОПиУ»', max_length=100)),
                ('cf_article', models.CharField(help_text='Статья ОДДС или «Не влияет на ОДДС»', max_length=100)),
                ('cf_section', models.CharField(blank=True, help_text='Раздел ОДДС', max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_types', to='accounts.shop')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('counterparty', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('accrual', models.FloatField(default=0, help_text='Сумма начисления для ОПиУ, сом')),
                ('cash', models.FloatField(default=0, help_text='Фактическое движение денег для ОДДС, сом')),
                ('method', models.CharField(blank=True, help_text='Метод оплаты', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='accounts.shop')),
                ('op_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='techcards.operationtype')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='operationtype',
            constraint=models.UniqueConstraint(fields=('shop', 'name'), name='optype_name_per_shop'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['shop', 'date'], name='techcards_o_shop_id_0ced9f_idx'),
        ),
    ]
