# Generated by Django 6.0.7 on 2026-07-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcards', '0004_finalproduct_category_finalproduct_manual_unit_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationtype',
            name='is_legacy',
            field=models.BooleanField(default=False, help_text='Только для импорта истории, недоступен для ручного ввода'),
        ),
    ]
