# Generated by Django 6.0.7 on 2026-07-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_role_tech_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('cashier', 'Кассир'), ('admin', 'Менеджер'), ('tech_admin', 'Тех. админ'), ('storekeeper', 'Складовщик / закупщик'), ('production', 'Производство / цех'), ('seller', 'Продавец')], default='cashier', max_length=20),
        ),
    ]
