# Generated by Django 4.2.11 on 2026-07-02 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('text', models.TextField(max_length=250)),
                ('footer_text', models.CharField(blank=True, default='', max_length=80)),
                ('background_type', models.CharField(choices=[('hearts', 'Сердечки'), ('snow', 'Снегопад'), ('confetti', 'Конфетти'), ('bubbles', 'Пузырьки'), ('stars', 'Звёзды')], default='hearts', max_length=20)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('video_start', models.FloatField(default=0)),
                ('video_end', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cards', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='accounts.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
