# Generated by Django 4.2.11 on 2026-07-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='background_type',
            field=models.CharField(choices=[('hearts', 'Сердечки'), ('snow', 'Снегопад'), ('confetti', 'Конфетти'), ('bubbles', 'Пузырьки'), ('stars', 'Звёзды'), ('petals', 'Лепестки'), ('fireworks', 'Салют'), ('balloons', 'Шарики'), ('gold', 'Золото')], default='hearts', max_length=20),
        ),
    ]
